#########################################################
##  Edit this file to configure the monitoring cluster ##
##  whole configuration template can be found under:   ##
##        LibreNMS-Helm/librenms/values.yaml           ##
#########################################################

global:
  TZ: "Atlantic/Reykjavik"
  company:
    name: "TEST CO"

ingress:
  # You need to install a cert if your turn on HTTPS:
  # nms cert <certificate-file> <key-file>
  https: false

storage:
  path: "/data/"

application:
  host:
    FQDN: "nms.test.local"
    # volumSize can not be edited after inital install.
    volumeSize: "20Gi"
  SNMPcommunity: 
    - "community-string-1"
    - "community-string-2"
  dispatcher:
    replicas: "1"

# DB info not be changed after inital install.
mariadb:
  credentials:
    rootPassword: "fooRootPassword"
    user: "foo"
    password: "bar"

msmtpd:
  enable: false
  host:
    name: "msmtpd"
    FQDN: "smtp.gmail.com"
    port: "587"
  from: "foo@gmail.com"
  credentials:
    email:
      user: "foo"
      password: "bar"   

smokeping:
  enable: false
  host:
    FQDN: "smokeping.test.local"

oxidized:
  enable: true
  image: "oxidized/oxidized:0.29.1-12-gdab52d0"
  host:
    FQDN: "ox.test.local"
  credentials:
    # token needs to be generated inside LibreNMS run "nms edit" 
    # to update this infromation after server is runnin.
    token: "API-token-generated-inside-LIBRE"
    
  group:
    core:
      user: "deviceadmin"
      password: "devicepassword"
    G1:
      user: ""
      password: ""
      string: "/^ox-group-1/"
    G2:
      user: ""
      password: ""
      string: "/^ox-group-2/"
    G3:
      password: ""
      pass: ""
      string: "/^ox-group-3/"
    G4:
      password: ""
      pass: ""
      string: "/^ox-group-4/"
    G5:
      user: ""
      password: ""
      string: "/^ox-group-5/"

xmatters:
  enable: false
  URL: "company.xmatters.com"
  APIkey: ""
  APIsecret: ""
