#########################################################
##  Edit this file to configure the monitoring cluster ##
##  whole configuration template can be found under:   ##
##        LibreNMS-Helm/librenms/values.yaml           ##
#########################################################

global:
  TZ: "Atlantic/Reykjavik"
  company:
    name: "Example Company"

ingress:
  # You need to install a cert if your turn on HTTPS:
  # nms cert <certificate-file> <key-file>
  https: false

storage:
  path: "/data/"

application:
  host:
    FQDN: "nms.example.local"
    # volumeSize cannot be changed after initial install.
    volumeSize: "20Gi"
  SNMPcommunity: 
    - "community-string-1"
    - "community-string-2"
  dispatcher:
    replicas: "1"

# DB info should not be changed after initial install.
mariadb:
  credentials:
    rootPassword: "change-me-root-password"
    user: "librenms"
    password: "change-me-db-password"

msmtpd:
  enable: false
  host:
    name: "msmtpd"
    FQDN: "smtp.gmail.com"
    port: "587"
  from: "noreply@example.com"
  credentials:
    email:
      user: "smtp-user"
      password: "change-me-smtp-password"

smokeping:
  enable: false
  host:
    FQDN: "smokeping.test.local"

oxidized:
  enable: true
  image: "oxidized/oxidized:0.29.1-12-gdab52d0"
  host:
    FQDN: "ox.test.local"
  credentials:
    # token needs to be generated inside LibreNMS. Run "nms edit"
    # to update this information after server is running.
    token: "API-token-generated-inside-LIBRE"
    
  group:
    core:
      user: "oxidized-user"
      password: "change-me-oxidized-password"
    G1:
      user: ""
      password: ""
      string: "/^ox-group-1/"
    G2:
      user: ""
      password: ""
      string: "/^ox-group-2/"
    G3:
      user: ""
      password: ""
      string: "/^ox-group-3/"
    G4:
      user: ""
      password: ""
      string: "/^ox-group-4/"
    G5:
      user: ""
      password: ""
      string: "/^ox-group-5/"

xmatters:
  enable: false
  URL: "company.xmatters.com"
  APIkey: ""
  APIsecret: ""
